# Generated by Django 2.0.4 on 2018-04-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_auto_20180420_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airport.Airplane'),
        ),
    ]
