# Generated by Django 2.0.4 on 2018-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_auto_20180420_0712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightPassenger',
            new_name='Ticket',
        ),
    ]
